export const AuthRegister = "https://localhost:7226/api/Auth/Register"
export const AuthLogin = "https://localhost:7226/security/createToken"
export const GetCategories = "https://localhost:7226/api/Home/getAllCategories"
export const GetStories = "https://localhost:7226/api/Home/getAllStories"
export const GetHistory = "https://localhost:7226/api/Home/history"
export const GetUserProfile = "https://localhost:7226/api/Home/userprofile"
export const GetStoryDetail = "https://localhost:7226/api/Home/getStoryDetail/"
export const GetChapterDetail = "https://localhost:7226/api/Home/getChapterDetail/"